apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-kustom
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: terraform-resources
    namespace: flux-system
  path: "./clusters/flux-system"
  prune: true
  wait: true
  timeout: 10m
