apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ansible-app
  namespace: flux-system
spec:
  interval: 1m # 1分おきにリポジトリをチェック
  path: "./"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: ansible-resources # 前述のGitRepositoryリソース名
  # ↓ これが重要：Git更新時に既存のJobがあっても強制的に出し直す
  force: true